1 Import Library

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

2. Import dataset

In [11]:
dataset = pd.read_csv('/content/data_dummy_preprocessing.csv')

X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

print(X)
print(y)

[[20.0 'Yogyakarta']
 [21.0 'Sleman']
 [19.0 'Bantul']
 [22.0 'Kulon Progo']
 [20.0 'Gunungkidul']
 [21.0 'Yogyakarta']
 [nan 'Sleman']
 [20.0 'Bantul']
 [22.0 'Kulon Progo']
 [21.0 'Gunungkidul']
 [19.0 'Yogyakarta']
 [20.0 nan]
 [22.0 'Bantul']
 [21.0 'Kulon Progo']
 [23.0 'Gunungkidul']]
['Aktif' 'Aktif' 'Tidak Aktif' 'Aktif' 'Tidak Aktif' 'Aktif' 'Aktif'
 'Tidak Aktif' 'Aktif' 'Tidak Aktif' 'Aktif' 'Aktif' 'Tidak Aktif' 'Aktif'
 'Tidak Aktif']


3. Menghilangkan Missing Value (UMUR)

In [15]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(
    missing_values=np.nan,
    strategy='mean'
)

X[:, 0:1] = imputer.fit_transform(X[:, 0:1])

print(X)

[[20.0 'Yogyakarta']
 [21.0 'Sleman']
 [19.0 'Bantul']
 [22.0 'Kulon Progo']
 [20.0 'Gunungkidul']
 [21.0 'Yogyakarta']
 [20.785714285714285 'Sleman']
 [20.0 'Bantul']
 [22.0 'Kulon Progo']
 [21.0 'Gunungkidul']
 [19.0 'Yogyakarta']
 [20.0 nan]
 [22.0 'Bantul']
 [21.0 'Kulon Progo']
 [23.0 'Gunungkidul']]


4. Menghilangkan Missing Value (kota)

In [16]:
imputer2 = SimpleImputer(strategy='most_frequent')

X[:, 1:2] = imputer2.fit_transform(X[:, 1:2])

print(X)

[[20.0 'Yogyakarta']
 [21.0 'Sleman']
 [19.0 'Bantul']
 [22.0 'Kulon Progo']
 [20.0 'Gunungkidul']
 [21.0 'Yogyakarta']
 [20.785714285714285 'Sleman']
 [20.0 'Bantul']
 [22.0 'Kulon Progo']
 [21.0 'Gunungkidul']
 [19.0 'Yogyakarta']
 [20.0 'Bantul']
 [22.0 'Bantul']
 [21.0 'Kulon Progo']
 [23.0 'Gunungkidul']]


5. Encoding Data Kategori (atribut)

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [1])
    ],
    remainder='passthrough'
)

X = np.array(ct.fit_transform(X))

print(X)


[[1.0 0.0 0.0 0.0 0.0 1.0 20.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 21.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 19.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 22.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 21.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 20.785714285714285]
 [1.0 0.0 1.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 22.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 21.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 19.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 22.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 21.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 23.0]]


6. Encoding Data Kategori (class/label)

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

print(y)

[0 0 1 0 1 0 0 1 0 1 0 0 1 0 1]


7. Membagi dataset ke training set dan test set

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1
)

print(X_train)
print(X_test)

print(y_train)
print(y_test)

[[1.0 0.0 1.0 0.0 0.0 0.0 19.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 19.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 21.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 21.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 20.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 23.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 21.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 22.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 22.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 21.0]]
[[1.0 0.0 0.0 1.0 0.0 0.0 22.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 20.785714285714285]]
[1 0 1 0 0 0 1 1 0 1 0 0]
[0 1 0]


8. Feature Scaling

In [21]:
print(X_train.shape)
print(X_train[:5])

(12, 7)
[[1.0 0.0 1.0 0.0 0.0 0.0 19.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 19.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 20.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 21.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 21.0]]
